# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ba444d167cddb12bdc2d5a2204ff366b5513a129a58006a45f43a414eb844eec13ae6f6cf395608ef83e3cbe7bbceebab30fdb0b5b518b32898c49d4cb72cc7

test:
  secret_key_base: 0ffba29f02af26a63341bddb6479d4578838de41f92cd329c617c558baa24da1a84e2c7a828a709bfc86a184ed50309f9fe54b2aa6469fa16ee81d9a6826847c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
